name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Add this line to grant id-token permission
  contents: read   # This is typically included to read repository contents

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the project
      run: |
        # Your build commands here

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages-artifact
        path: path/to/your/build/artifacts

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages-artifact
